### ISSUE TITLE
Docker file not run-able

### ISSUE THREAD

**Issue by Lr-2002** [BaratiLab/MeshDQN#1]
I've download your docker File and run into it
While the bash tell me "no torch"
Could you tell me What's wrong with me ?

**Comment by CoopLo** [comment]
Hello,

I am having the same issue, but not sure why. I don't recall this issue when testing the image before publishing. In any case, I have been able to install the various required packages in the provided docker image as `pip install [package] --user` for `torch`, `pyyaml`, `pandas`, `ray`, `tabulate`, `gym`, `tqdm`, `torch-geometric`, 'torch_sparse`, `torch_scatter`, `shapely` (and any other I may have missed). This is pretty quick, aside from `torch_sparse` and `torch_scatter` which may take a few minutes. After that, you may need to modify some paths in your config file, `airfoil_dqn.py`, and `Env2DAirfoil.py`, but it should run. Please let me know if you have any other issues

**Comment by Lr-2002** [comment]
Do you mean that I should install the files by myself? 
the dolfin was not easy to install to be honest

**Comment by Lr-2002** [comment]
ok The problem has been solved and it's running now. Thanks a lot

**Comment by xuliji** [comment]
> ok The problem has been solved and it's running now. Thanks a lot

Could you please explain how dolfin was installed? Thank you very much.

**Comment by CoopLo** [comment]
I used docker and singularity images that had fenics installed already (either provided by a labmate or the fenics website, I don't remember). I tried installing with pip/conda but never got it to work
