### ISSUE TITLE
Some Problem?

### ISSUE THREAD

**Issue by Lr-2002** [BaratiLab/MeshDQN#2]
Hello, I'm re-reading your paper for some puzzle .
May you help me ?
1. What will the model do if you trained it.?Will it be useful for speed acceleration?
2. How to re-use the model  for Inferece, Could it be use for the next frame  generation of the airfoil-CFD？

**Comment by CoopLo** [comment]
1. A trained model will be useful for coarsening a mesh. This will help speed up simulation time in a traditional numerical solver
2. The trained model cannot be used for next frame generation. A model could be trained on multiple airfoil meshes simultaneously and be used for coarsening other airfoil meshes, but we did not test this

**Comment by Lr-2002** [comment]
ok
Thanks for your feedback

It'll be very cool if one model could accelerate more CFD problem solving ~~~
