### ISSUE TITLE
I would like to ask how to install the dolfin package

### ISSUE THREAD

**Issue by xuliji** [BaratiLab/MeshDQN#3]
I would like to ask how to install the dolfin package. Thank you

**Comment by CoopLo** [comment]
The provided docker image should have dolfin installed by default. If not, there are usage guides through the fenics [website](https://fenics.readthedocs.io/projects/containers/en/latest/introduction.html#running-fenics-in-docker). I believe I used the 2019 version of fenics/dolfin for this project
